server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.193.218.79:13658/hctools?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: ENC(7jn6lUeSJSrUJ35F1/FB+Q==)
    password: ENC(th8n8WbsZmoTo5Y3TicwfG37ryEenAyv)